// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYcPVm1OkwMCMwnunr4uVw36g-6PuDCpo',
    appId: '1:1082833164860:web:7a1a47365ba490d1fd8139',
    messagingSenderId: '1082833164860',
    projectId: 'openweather-82347',
    authDomain: 'openweather-82347.firebaseapp.com',
    storageBucket: 'openweather-82347.firebasestorage.app',
    measurementId: 'G-FZ2MFHNKH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq2elQ8zRW03LTU0S7KLbyfa1ReUdMyWc',
    appId: '1:1082833164860:android:c4dd1eb9f26d4770fd8139',
    messagingSenderId: '1082833164860',
    projectId: 'openweather-82347',
    storageBucket: 'openweather-82347.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvMDiFVxT30e_AG4tcZiOucZZrb5QUgdE',
    appId: '1:1082833164860:ios:381b453b77befeb5fd8139',
    messagingSenderId: '1082833164860',
    projectId: 'openweather-82347',
    storageBucket: 'openweather-82347.firebasestorage.app',
    iosBundleId: 'com.example.projetOpenwetherMap',
  );
}
